baseURL: https://philippewebsite99.netlify.app
languageCode: en-us
title: Philippe
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
     This is my portfolio website
    title: Hi, my name is Philippe
  blog: {}
  contact:
    address:
      - city: Koudougou
        country: Burkina Faso
        street: Palogo
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: yameogophilippe3@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+226) 64-34-75-31
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: By Philippe Yameogo
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100008694165424
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/philippe.yameogo/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/philippe9-coder
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    #button1:
      #- name: Get Started
       # url: blogs
    #button2:
      #- name: Log In
       # url: '#'
    links:
      - name: Accueil
        url: '#'
      - name: Search
        url: blogs/aliquam
      - name: Our_Product
        url: blogs/tempus
      - name: Evenements
        url: blogs/magna
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Top beer and wine consumption
        title: Where do people drink the most?
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Maintenance en Informatique
        title: Graphism
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Detente
        title: Plage
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nature
        title: Picture
        url: blogs/About
      - image: pic05.jpg
        subtitle: Object d'art
        title: Art
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Hi!
I am responding on behalf of Philippe YAMEOGO, a student at Burkina Institute of Technology (BIT), who is completing my third year of computer engineering.
During my studies, I really liked the very advanced training I had in computer tools. On top of that, I really enjoyed the leadership courses which allowed me to develop a fairly high level of dynamism and a sense of responsibility.

All my thanks go to the place of the administration of BIT, my teachers and my comrades. And the best is yet to come BIT.

."
    title: About Us
    url: blogs
